config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :converters
  
  root 'welcome#index'
end

app/models/converter.rb
class Converter < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/converters_controller.rb
class ConvertersController < ApplicationController
  before_action :set_converter, only: [:show, :edit, :update, :destroy]

  def index
    @converters = Converter.all
  end

  def show
  end

  def new
    @converter = Converter.new
  end

  def edit
  end

  def create
    @converter = Converter.new(converter_params)

    respond_to do |format|
      if @converter.save
        format.html { redirect_to @converter, notice: 'Converter was successfully created.' }
        format.json { render :show, status: :created, location: @converter }
      else
        format.html { render :new }
        format.json { render json: @converter.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @converter.update(converter_params)
        format.html { redirect_to @converter, notice: 'Converter was successfully updated.' }
        format.json { render :show, status: :ok, location: @converter }
      else
        format.html { render :edit }
        format.json { render json: @converter.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @converter.destroy
    respond_to do |format|
      format.html { redirect_to converters_url, notice: 'Converter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_converter
      @converter = Converter.find(params[:id])
    end

    def converter_params
      params.require(:converter).permit(:fromCurrency, :toCurrency)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/converters_helper.rb
module ConvertersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/converters/_form.html.erb
<%= form_for(@converter) do |f| %>
  <% if @converter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@converter.errors.count, "error") %> prohibited this converter from being saved:</h2>

      <ul>
      <% @converter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fromCurrency %><br>
    <%= f.text_field :fromCurrency %>
  </div>
  <div class="field">
    <%= f.label :toCurrency %><br>
    <%= f.text_field :toCurrency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/converters/edit.html.erb
<h1>Editing Converter</h1>

<%= render 'form' %>

<%= link_to 'Show', @converter %> |
<%= link_to 'Back', converters_path %>

app/views/converters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Converters</h1>

<table>
  <thead>
    <tr>
      <th>Fromcurrency</th>
      <th>Tocurrency</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @converters.each do |converter| %>
      <tr>
        <td><%= converter.fromCurrency %></td>
        <td><%= converter.toCurrency %></td>
        <td><%= link_to 'Show', converter %></td>
        <td><%= link_to 'Edit', edit_converter_path(converter) %></td>
        <td><%= link_to 'Destroy', converter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Converter', new_converter_path %>

app/views/converters/new.html.erb
<h1>New Converter</h1>

<%= render 'form' %>

<%= link_to 'Back', converters_path %>

app/views/converters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fromcurrency:</strong>
  <%= @converter.fromCurrency %>
</p>

<p>
  <strong>Tocurrency:</strong>
  <%= @converter.toCurrency %>
</p>

<%= link_to 'Edit', edit_converter_path(@converter) %> |
<%= link_to 'Back', converters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleSoapApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>